apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tax-calculator
spec:
  selector:
    app: tax-calculator
    component: backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
