apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tax-calculator
  labels:
    app: tax-calculator
    component: backend
spec:
  type: LoadBalancer
  selector:
    component: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
