apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    # Vault Configuration
    ui = true
    
    listener "tcp" {
      address         = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable     = 1
    }
    
    storage "raft" {
      path = "/vault/data"
    }
    
    seal "awskms" {
      region     = "eu-west-2"
      kms_key_id = "<KMS_KEY_ID>"
    }
