apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tax-calculator

resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
